name: Scrape latest NYC data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '4,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data and merge it into a dated CSV
      run: |-
        (cd nyc-coronavirus-data/ && python scrape.py)
        (cd nyc-coronavirus-data/ && python merge_csvs.py)
    - name: Commit and push if it changed
      run: |-
        ls
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        timestamp=$(date -u +"%Y-%m-%d")
        git add -A
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
