name: Scrape latest NYC data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '4,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://raw.githubusercontent.com/nychealth/coronavirus-data/master/recent/recent-4-week-by-modzcta.csv > recent-4-week-by-modzcta.csv
    - name: Commit and push if it changed
      run: |-
        ls
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        timestamp=$(date -u +"%m-%d-%Y")
        mv recent-4-week-by-modzcta.csv nyc-coronavirus-data/raw/${timestamp}.csv
        git add -A
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
